import { Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";

// Inter sebagai pengganti Geist Sans
const inter = Inter({
  variable: "--font-geist-sans", // Variabel tetap sama supaya CSS kamu tidak rusak
  subsets: ["latin"],
});

// JetBrains Mono sebagai pengganti Geist Mono
const jetbrainsMono = JetBrains_Mono({
  variable: "--font-geist-mono", // Variabel tetap sama supaya CSS kamu tidak rusak
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${jetbrainsMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
